### ISSUE TITLE
Transparency problem

### ISSUE THREAD

**Issue by Boopideedoo** [Seefaaa/aseprite-dmi#7]
I am unable to make the state of the dmi file transparent when needed as aesprite loves to not allow it to how its supposed to be. Mind taking a look at it and seeing if anything can be done to fix it?

**Comment by Seefaaa** [comment]
Normally, you can make states transparent. Its only rendered wrong in dialog and thats Aseprite's issue since you cannot draw transparent on dialog canvas. Aseprite messes up the alpha channel of the image when drawing it to the canvas.

But you can still save transparency even if its looking wrong on dialog.
So I made a workaround for this and currenly this is the best  I can do.

See [this post](https://community.aseprite.org/t/unable-to-draw-to-transparent-image-to-dlg-canvas/19406) on Aseprite's forum.

This is what it looks like when I include the alpha channel in dialog:
![image](https://github.com/Seefaaa/aseprite-dmi/assets/50076109/a61cdfcb-2243-4d64-991f-719f33053f22)

This is what I can achieve best in dialog:
![image](https://github.com/Seefaaa/aseprite-dmi/assets/50076109/348f272b-7233-4dd5-9128-6396149b8aa1)

This is how it is actually when you open the state in editor:
![image](https://github.com/Seefaaa/aseprite-dmi/assets/50076109/4baeb19f-f58a-4ff0-807e-3e824a0c8f61)

This is the proof that it works fine in Dream Maker:
![image](https://github.com/Seefaaa/aseprite-dmi/assets/50076109/aa465ca2-9f8d-412e-84e0-47265b1e5038)

**Comment by Boopideedoo** [comment]
Ah ok thanks for letting me know! I will try the same workaround.

**Comment by Seefaaa** [comment]
I have now completely fixed this problem in here 9fd155e0a4ba3bc0ea0cf26fa294cee5b5f8de47  and it will be fixed properly in the next release.
